sbatch bashfolder/det2dyn/trainkp_3_kp2dyn.sh
sbatch bashfolder/det2dyn/trainkp_5_kp2dyn.sh
sbatch bashfolder/det2dyn/trainkp_10_kp2dyn.sh
sbatch bashfolder/det2dyn/trainkp_15_kp2dyn.sh
sbatch bashfolder/det2dyn/trainkp_20_kp2dyn.sh
sbatch bashfolder/det2dyn/trainkp_25_kp2dyn.sh
sbatch bashfolder/det2dyn/trainkp_30_kp2dyn.sh
sbatch bashfolder/det2dyn/trainkp_35_kp2dyn.sh
sbatch bashfolder/det2dyn/trainkp_40_kp2dyn.sh
sbatch bashfolder/det2dyn/trainkp_45_kp2dyn.sh
sbatch bashfolder/det2dyn/trainkp_50_kp2dyn.sh
sbatch bashfolder/det2dyn/trainkp_55_kp2dyn.sh
sbatch bashfolder/det2dyn/trainkp_60_kp2dyn.sh