sbatch bashfolder/det2comp/trainkp_3_kp2comp.sh
sbatch bashfolder/det2comp/trainkp_5_kp2comp.sh
sbatch bashfolder/det2comp/trainkp_10_kp2comp.sh
sbatch bashfolder/det2comp/trainkp_15_kp2comp.sh
sbatch bashfolder/det2comp/trainkp_20_kp2comp.sh
sbatch bashfolder/det2comp/trainkp_25_kp2comp.sh
sbatch bashfolder/det2comp/trainkp_30_kp2comp.sh
sbatch bashfolder/det2comp/trainkp_35_kp2comp.sh
sbatch bashfolder/det2comp/trainkp_40_kp2comp.sh
sbatch bashfolder/det2comp/trainkp_45_kp2comp.sh
sbatch bashfolder/det2comp/trainkp_50_kp2comp.sh
sbatch bashfolder/det2comp/trainkp_55_kp2comp.sh
sbatch bashfolder/det2comp/trainkp_60_kp2comp.sh