sbatch trainkp_3_comp.sh
sbatch trainkp_5_comp.sh
sbatch trainkp_10_comp.sh
sbatch trainkp_15_comp.sh
sbatch trainkp_20_comp.sh
sbatch trainkp_25_comp.sh
sbatch trainkp_30_comp.sh
sbatch trainkp_35_comp.sh
sbatch trainkp_40_comp.sh
sbatch trainkp_45_comp.sh
sbatch trainkp_50_comp.sh
sbatch trainkp_55_comp.sh
sbatch trainkp_60_comp.sh