sbatch bashfolder/trainkp_3_comp.sh
sbatch bashfolder/trainkp_5_comp.sh
sbatch bashfolder/trainkp_10_comp.sh
sbatch bashfolder/trainkp_15_comp.sh
sbatch bashfolder/trainkp_20_comp.sh
sbatch bashfolder/trainkp_25_comp.sh
sbatch bashfolder/trainkp_30_comp.sh
sbatch bashfolder/trainkp_35_comp.sh
sbatch bashfolder/trainkp_40_comp.sh
sbatch bashfolder/trainkp_45_comp.sh
sbatch bashfolder/trainkp_50_comp.sh
sbatch bashfolder/trainkp_55_comp.sh
sbatch bashfolder/trainkp_60_comp.sh